---
apiVersion: v1
kind: Service
metadata:
  name: postgres-deployment-service
  labels:
    name: postgres-deployment-service
    app: voting-project
spec:
  type: ClusterIP
  ports:
    - targetPort: 5432
      port: 5432
  selector:
    name: postgres-deployment
    app: voting-project
...
