---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: result-deployment
  labels:
    name: result-deployment
    app: voting-project
spec:
  replicas: 1
  selector:
    matchLabels:
      name: result-deployment
      app: voting-project
  template:
    metadata:
      name: result-deployment
      labels:
        name: result-deployment
        app: voting-project
    spec:
      containers:
        - name: result-deployment
          image: dockersamples/examplevotingapp_result
          ports:
            - containerPort: 80

...