---
apiVersion: v1
kind: Service
metadata:
  name: result-deployment-service
  labels:
    name: result-deployment-service
    app: voting-project
spec:
  type: LoadBalancer
  ports:
    - targetPort: 80
      port: 80
  selector:
    name: result-deployment
    app: voting-project
...
