---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: voting-deployment
  labels:
    name: voting-deployment
    app: voting-project
spec:
  replicas: 2
  selector:
    matchLabels:
      name: voting-deployment
      app: voting-project
  template:
    metadata:
      name: voting-pod
      labels:
        name: voting-deployment
        app: voting-project
    spec:
      containers:
        - name: voting-deployment
          image: dockersamples/examplevotingapp_vote
          ports:
            - containerPort: 80


...
