---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-deployment
  labels:
    name: worker-deployment
    app: voting-project
spec:
  replicas: 1
  selector:
    matchLabels:
      name: worker-deployment
      app: voting-project
  template:
    metadata:
      name: worker-deployment
      labels:
        name: worker-deployment
        app: voting-project
    spec:
      containers:
        - name: worker-deployment
          image: dockersamples/examplevotingapp_worker
...
